In [1]:
import sqlite3
import pandas as pd

In [2]:
con = sqlite3.connect('imdb_small_indexed.db')
cur = con.cursor()

Посмотрим, в каких жанрах снимался Райан Гослинг.

In [3]:
gosling_genres_query = """
SELECT
	genre_name,
	COUNT(genre_id) as n_genre_films
FROM titles 
	JOIN crew ON titles.title_id = crew.title_id
	JOIN people ON crew.person_id = people.person_id
	JOIN film_genres ON titles.title_id = film_genres.title_id
	JOIN genre_types ON film_genres.genre_id = genre_types.id
WHERE name = "Ryan Gosling"
GROUP BY genre_id
ORDER BY n_genre_films DESC
"""

In [4]:
df = pd.read_sql_query(gosling_genres_query, con=con)

In [5]:
df

     genre_name  n_genre_films
0         Drama             24
1         Crime              8
2        Action              7
3      Thriller              6
4       Mystery              6
5        Comedy              6
6       Romance              5
7   Documentary              5
8     Biography              4
9         Music              2
10       Horror              2
11      Fantasy              2
12    Adventure              2
13    Talk-Show              1
14        Sport              1
15       Sci-Fi              1
16   Reality-TV              1
17      History              1